name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']          # Следим за CI
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results    # Имя артефакта из первого файла
          name: JEST Tests
          path: '*.xml'             # Ищем XML внутри артефакта
          reporter: jest-junit